
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-02T08:15:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3b6d99b8ebec4f564f7ba835936492ae099975e",
 "version": "0.7.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
